apiVersion: v2
name: yas-platform
description: Umbrella Helm chart for YAS (Yet Another Shop)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: yas-configuration
    version: 0.4.0
    repository: file://../yas-configuration

  - name: product
    version: 0.1.0
    repository: file://../product

  - name: media
    version: 0.1.0
    repository: file://../media

  - name: location
    version: 0.1.0
    repository: file://../location

  - name: customer
    version: 0.1.0
    repository: file://../customer

  - name: cart
    version: 0.1.0
    repository: file://../cart

  - name: inventory
    version: 0.1.0
    repository: file://../inventory

  - name: rating
    version: 0.1.0
    repository: file://../rating

  - name: promotion
    version: 0.1.0
    repository: file://../promotion

  - name: tax
    version: 0.1.0
    repository: file://../tax

  - name: order
    version: 0.1.0
    repository: file://../order

  - name: payment
    version: 0.1.0
    repository: file://../payment

  - name: storefront-bff
    version: 0.1.0
    repository: file://../storefront-bff

  - name: storefront-ui
    version: 0.1.0
    repository: file://../storefront-ui

  - name: backoffice-bff
    version: 0.1.0
    repository: file://../backoffice-bff

  - name: backoffice-ui
    version: 0.1.0
    repository: file://../backoffice-ui